name: pandp
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  enum_to_string: ^1.0.14
  provider: ^4.3.3
  flutter_markdown: any
  google_fonts: ^1.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/story.md
    - assets/dummy.md
    - assets/story_person/
    - assets/img/
