name: pandp
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  flutter_markdown: any
  google_fonts: ^1.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/story.md
    - assets/img/chart.png
    - assets/img/label_alpha.png
    - assets/img/label_bravo.png
    - assets/img/label_charly.png
    - assets/img/wappen_neu_anfang.png
    - assets/img/wappen_neu_farmland.png
    - assets/img/wappen_nord_wall.png
    - assets/img/wappen_rhin_hafen.png
    - assets/img/wappen_siedlung.png
    - assets/img/wappen_spezial_einheit.png
    - assets/img/wappen_west_defense.png

